export const MOTIVATIONAL_QUOTES = [
  "Success comes with hard work.",
  "The cost of growth is facing discomfort.",
  "Perseverance is priceless.",
  "Chase your dreams, no matter the cost.",
  "Small progress every day is worth the price.",
  "Time is the most valuable asset you can invest.",
  "Failure is just the cost of learning.",
  "Fear costs you more than failure ever will.",
  "Great things take time and patience.",
  "Your effort today pays off tomorrow.",
  "Don't let fear stop you from seizing opportunities.",
  "Change comes with its price, but it’s worth it.",
  "Follow your passion, even if it costs you comfort.",
  "Consistency pays the highest dividends.",
  "Great rewards come with great risks.",
  "Facing challenges is the price of personal growth.",
  "Discomfort today leads to strength tomorrow.",
  "Chasing dreams costs energy, but it's always worth it.",
  "Invest your focus; it's your most powerful tool.",
  "Effort is never wasted, even if you fail.",
  "Practice is the most valuable investment in success.",
  "Sacrifice today for a better tomorrow.",
  "Resilience is a skill you pay for with persistence.",
  "The price of learning is continuous growth.",
  "A positive mindset is priceless.",
  "Dedication pays in ways money can't buy.",
  "Every failure is an opportunity in disguise.",
  "Courage costs nothing but pays off forever.",
  "Invest in clarity, and the path ahead becomes easier.",
  "Comfort zones have the highest costs—stay uncomfortable.",
  "Experience is earned, not bought.",
  "Every decision has a cost—make them count.",
  "Self-belief is a priceless asset.",
  "Focus is free but extremely valuable.",
  "Don’t wait for the perfect time; the cost of waiting is opportunity.",
  "Taking action today is an investment in tomorrow.",
  "Obstacles are opportunities to grow, not a cost to avoid.",
  "Resilience is the cost of staying in the game.",
  "Consistency costs time but yields great rewards.",
  "A growth mindset is priceless.",
  "Preparation is the key to success, and the cost is effort.",
  "Taking initiative today will reward you in the future.",
  "Patience is costly, but it always pays off.",
  "Persistence pays the highest price for success.",
  "Confidence costs nothing but builds everything.",
  "Commitment today brings results tomorrow.",
  "What you do today matters more than the cost of trying.",
  "Your vision’s price is the energy and effort you put in.",
  "Risk is the price of innovation.",
  "A mindset shift costs you comfort but changes your life.",
  "Ambition is priceless, but it comes with sacrifices.",
  "Accountability today creates success tomorrow.",
  "Success requires a balance between cost and reward.",
  "Leadership is earned through action, not position.",
  "Gratitude costs nothing but pays you back a thousandfold.",
  "Empowerment comes at the cost of taking responsibility.",
  "Discipline costs comfort but reaps reward.",
];
